User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
> conda --version
> conda info --json
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> pyenv root
> conda env list
Error 2020-09-06 15:53:28: Failed to get conda environment list from conda [Error: spawn conda ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn conda',
  path: 'conda',
  spawnargs: [ 'env', 'list' ]
}
Error 2020-09-06 15:53:28: Failed to download and store experiments, Class name = b, completed in 2168ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 404, Not Found, Uri https://raw.githubusercontent.com/microsoft/vscode-python/master/experiments.json
	at H._callback (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/extension.js:54:713175)
	at H.a._callback.a.callback.a.callback (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:203:13)
	at H.<anonymous> (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:203:13)
	at IncomingMessage.<anonymous> (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:291:20)
	at IncomingMessage.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)]
Error 2020-09-06 15:53:28: Failed to initialize experiments, Class name = b, completed in 2173ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 404, Not Found, Uri https://raw.githubusercontent.com/microsoft/vscode-python/master/experiments.json
	at H._callback (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/extension.js:54:713175)
	at H.a._callback.a.callback.a.callback (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:5442)
	at H.emit (events.js:203:13)
	at H.<anonymous> (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:18302)
	at H.emit (events.js:203:13)
	at IncomingMessage.<anonymous> (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/node_modules/request.js:189:17134)
	at Object.onceWrapper (events.js:291:20)
	at IncomingMessage.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)] {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ]
}
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Error 2020-09-06 15:53:28: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/mulukou/Projects/bots-web-service/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/mulukou/Projects/bots-web-service/.vscode/settings.json')
	at _handleError (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:672:249)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async v.readText (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/extension.js:1:495817)
	at async p.doesFileNeedToBeFixed (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:953520)
	at async /home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952647
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952593)
	at async p.updateTestSettings (/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/out/client/extension.js:56:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Starting Jedi Python language engine.
Python interpreter path: /usr/bin/python
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> conda --version
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py
Error 2020-09-06 15:53:20: stderr jediProxy Error (stderr) /home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/Projects/bots-web-service/xlsx/test.py
cwd: ~/Projects/bots-web-service
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/Projects/bots-web-service/xlsx/test.py
cwd: ~/Projects/bots-web-service
Error 2020-09-06 15:53:25: stderr jediProxy Error (stderr) /home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

Error 2020-09-06 16:01:53: stderr jediProxy Error (stderr) /home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

Error 2020-09-06 16:01:55: stderr jediProxy Error (stderr) /home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

Error 2020-09-06 17:26:29: stderr jediProxy Error (stderr) /home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2020-09-06 17:26:29: stderr jediProxy Error (stderr) /home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2020-09-06 17:26:29: stderr jediProxy Error (stderr) /home/mulukou/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

